config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :services
  devise_for :users
  resources :rules
  resources :users
  get 'reverse', to: 'dns#reverse'
  get 'forward', to: 'dns#forward'

  root to: 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :services

  validates :name, :services, presence: true
  validates :name, length: { maximum: 20 }
  validates :name, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if params[:name].blank?
      @groups = Group.all
    else
      @groups = Group.select("id", "name").where("name LIKE ?", "#{params[:name]}%").order(:name).limit(10)

      @groups.each do |g|
        logger.debug("G: #{g.name}")
      end
      respond_to do |format|
        format.json { render json: @groups, :only => [:id, :name] }
      end
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group_services = "[]"
  end

  # GET /groups/1/edit
  def edit
    @group_services = @group.services.map do |item|
      [ item.id, item.name ]
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update

    # if size == 1 then only the empty value was passed.
    if params[:group][:service_ids].size == 1
      @group_services = @group.services.map do |item|
        [ item.id, item.name ]
      end
    else
      @group.services.clear
      params[:group][:service_ids] ||= []
      params[:group][:service_ids].each do |k,v|
        @group.services << Service.find(k) unless k.empty?
      end
      @group_services = @group.services.map do |item|
        [ item.id, item.name ]
      end
    end

    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, { :service_ids => []})
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="row">
      <%= f.label "service_ids", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
          <div class="input-group input-group-sm select2-bootstrap-prepend">
              <%= f.select :service_ids, {}, {}, { class: "form-control", multiple: true } %>
          </div>
      </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
function formatService(service) { return service.text }
function formatServiceSelection(service){ return service.text }

var $element = $("#group_service_ids").select2({
    placeholder: "Select a service...",
    ajax: {
        url: "<%= services_path(format: :json) %>",
        dataType: 'json',
        delay: 250,
        data: function (params) {
            return {
                name: params.term,
                page: params.page
            };
        },
        processResults: function (data, page) {
            var newData = [];
            data.forEach(function (i, item) {
                newData.push({
                    id: i.id,
                    text: i.name
                });
            });
            return { results: newData };
        },
        cache: true
    },
    theme: 'bootstrap',
    allowClear: true,
    escapeMarkup: function (markup) { return markup; },
    minimumInputLength: 1,
    templateResult: formatService,
    templateSelection: formatServiceSelection
});

var some_data = <%= raw @group_services || [] %>;

for (var d = 0; d < some_data.length; d++) {
    var item = some_data[d];
    var option = new Option(item[1], item[0], true, true);
    $element.append(option);
}
$element.trigger('change');

});

</script>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>