config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :services
  devise_for :users
  resources :rules
  resources :users
  get 'reverse', to: 'dns#reverse'
  get 'forward', to: 'dns#forward'

  root to: 'welcome#index'

end

app/models/rule.rb
require 'ASA'
require 'open3'
require 'resolv'
require 'uri'

class Rule < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :services
  has_and_belongs_to_many :groups

  before_validation :set_sport

  ACTIONS = %w(permit deny)

  validates :action, :src_addr, :dst_addr, presence: true

  validates :description, length: { maximum: 255 }
  validates :action, :inclusion => { :in => ACTIONS }
  validates :sport, :numericality => { :greater_than => 0,
                                       :less_than => 65536,
                                       :allow_blank => true }

  validate :presence_of_services_or_groups
  validate :valid_src, :valid_dst
  validate :valid_rule

  private

  def set_sport
    self.sport = rand(1025..65535) if self.sport.blank?
  end

  def default_port(uri)
    # Returns the default port for a given URI if it is known, else nil.
    _port = URI.parse(URI.encode(uri)).port
  rescue
  end

  def domain(uri)
    # Returns the domain with a URI scheme
    uri.gsub(/^[a-zA-Z]*:\/\//, '')
  end

  def hostname_ip(hostname)
    # Returns the IP of a domain.
    _domain = domain(hostname)
    _encoded = URI.encode(_domain)
    Resolv.getaddress(_encoded)
  rescue Resolv::ResolvError
  end

  def random_ip(network)
    # Returns a random IP address from a network.
    _net = NetAddr::CIDR.create(network)
    unless _net.netmask == "/32"
      _net = NetAddr::CIDR.create("#{_net.network}#{_net.netmask}")
      _net = _net[rand 1...(_net.size-1)]
    end
    _net.ip
  rescue ValidationError # Was not a valid IP.
  end

  def ip_address(address)
    # Returns an IP address from either the hostname or a network.
    if hostname_ip(address).nil?
      return random_ip(address)
    end
    hostname_ip(address)
  rescue
  end

  def valid_src
    NetAddr::CIDR.create(ip_address(src_addr))
  rescue
    self.errors[:base] << "The source address #{src_addr} is not valid."
  end

  def valid_dst
    NetAddr::CIDR.create(ip_address(dst_addr))
  rescue
    self.errors[:base] << "The destination address #{dst_addr} is not valid."
  end

  def interface(ipaddr)
    # TODO: interfaces should be obtained from the ASA.
    best = 2**32
    candidate = nil
    interfaces = {}
    interfaces["inside"] = [ "192.168.1.0/24" ]
    interfaces["outside"] = [ "193.191.187.0/25" ]
    interfaces["humanresources"] = [ "10.10.10.0/24" ]
    interfaces.each do |interface, subnets|
      subnets.each do |subnet|
        net = NetAddr::CIDR.create(subnet)
        if net.contains?(ipaddr) && net.size < best
          best = net.size
          candidate = interface
        end
      end
    end
    candidate
  end

  # A rule should have at least a group or a service linked to it.
  def presence_of_services_or_groups
    if services.blank? and self.groups.blank?
      self.errors[:base] << "Please select at least 1 service or group."
    end
  end

  def valid_rule
    unless self.errors.any?
      _random_src = ip_address(src_addr)
      _random_dst = ip_address(dst_addr)
      _interface = interface(_random_src) || "outside"
      logger.debug("INTERFACE: #{_interface}")
      begin
        asa = ASA.new(ENV["FW_IP"], ENV["FW_USER"], ENV["FW_PASSWORD"])
        asa.connect
        # code
        unless services.blank?
          self.services.each do |service|
            response = asa.query("tcp-udp", "hash", true, {
              :interface => "#{_interface}",
              :protocol => "#{service.protocol}",
              :sip => "#{_random_src}",
              :sport => "#{self.sport}",
              :dip => "#{_random_dst}",
              :dport => "#{service.port}"
            })
            unless response.nil?
              self.result = "#{response.inspect}"
              case response["result"]["action"]
              when "allow"
                errors[:base] << "The service '#{service.name}'\
                (#{service.protocol}-#{service.port})\
                is already allowed" if "#{action}" == "permit"
              when "drop"
                errors[:base] << "The service '#{service.name}'\
                (#{service.protocol}-#{service.port})\
                is already dropped" if "#{action}" == "deny"
              else
                # pass response to controller
              end
            end
          end
        end
        # GROUPS
        unless groups.blank?
          self.groups.each do |group|
            group.services.each do |service|
              logger.debug("Testing GroupService: #{service.name} for #{group.name}")
              response = asa.query("tcp-udp", "hash", true, {
                :interface => "#{_interface}",
                :protocol => "#{service.protocol}",
                :sip => "#{_random_src}",
                :sport => "#{self.sport}",
                :dip => "#{_random_dst}",
                :dport => "#{service.port}"
              })
              unless response.nil?
                self.result = "#{response.inspect}"
                case response["result"]["action"]
                when "allow"
                  errors[:base] << "The service '#{service.name}'\
                  (#{service.protocol}-#{service.port})\
                  is already allowed" if "#{action}" == "permit"
                when "drop"
                  errors[:base] << "The service '#{service.name}'\
                  (#{service.protocol}-#{service.port})\
                  is already dropped" if "#{action}" == "deny"
                else
                  #pass response to controller
                end
              end
            end
          end
        end
      rescue => e
        errors[:base] << e.message
      ensure
        asa.disconnect
      end
    end
  end

  public

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  before_action :set_actions, only: [ :new, :edit, :update, :create ]
  before_action :authenticate_user!

  # GET /rules
  # GET /rules.json
  def index
    @user = current_user
    if current_user.admin?
      @rules = Rule.all
    else
      @rules = current_user.rules
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @x = eval(@rule.result)
    @phases = @x["Phase"]
    @result = [ @x["result"] ]
  end

  # GET /rules/new
  def new
    @rule = Rule.new
    @rule_services = "[]"
    @rule_groups = "[]"
  end

  # GET /rules/1/edit
  def edit
    @rule_services = @rule.services.map do |item|
      [ item.id, item.name ]
    end
    @rule_groups = @rule.groups.map do |item|
      [ item.id, item.name ]
    end
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = current_user.rules.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html {
          redirect_to @rule, notice: 'Rule was successfully created.'
        }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    authorize @rule

    # if size == 1 then only the empty value was passed.
    if params[:rule][:service_ids].size == 1
      @rule_services = @rule.services.map do |item|
        [ item.id, item.name ]
      end
    else
      @rule.services.clear
      params[:rule][:service_ids] ||= []
      params[:rule][:service_ids].each do |k,v|
        @rule.services << Service.find(k) unless k.empty?
      end
      @rule_services = @rule.services.map do |item|
        [ item.id, item.name ]
      end
    end

    # if size == 1 then only the empty value was passed.
    if params[:rule][:group_ids].size == 1
      @rule_groups = @rule.groups.map do |item|
        [ item.id, item.name ]
      end
    else
      @rule.groups.clear
      params[:rule][:group_ids] ||= []
      params[:rule][:group_ids].each do |k,v|
        @rule.groups << Group.find(k) unless k.empty?
      end
      @rule_groups = @rule.groups.map do |item|
        [ item.id, item.name ]
      end
    end

    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    authorize @rule
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    def set_actions
      @actions = Rule::ACTIONS
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:description, :action, :src_addr, :sport, :dst_addr, {:service_ids => []}, {:group_ids => []})
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_for @rule, html: {class: "form-horizontal" } do |f| %>
  <% if @rule.errors.any? %>
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h3 class="panel-title"><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h3>
    </div>
    <div class="panel-body">
     <ul>
      <% @rule.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   </div>
  <% end %>

  <fieldset class="fieldset">
    <legend>General</legend>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :action, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.select :action, options_for_select(@actions.collect, @rule.action), {}, class: "form-control" %>
      </div>
    </div>

  </fieldset>

  <fieldset class="fieldset">
    <legend>Source</legend>

    <div class="form-group">
      <%= f.label :src_addr, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :src_addr, class: "form-control" %> 
      </div>
    </div>

    <div class="form-group">
        <div class="col-sm-2"></div>
        <small id="resolved_src" class="col-sm-10"></small>
    </div>

    <div class="form-group">
        <%= f.label :sport, class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
            <%= f.number_field :sport, class: "form-control" %>
        </div>
    </div>

  </fieldset>

  <fieldset class="fieldset">
    <legend>Destination</legend>

    <div class="form-group">
      <%= f.label :dst_addr, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :dst_addr, class: "form-control" %> 
      </div>
    </div>

    <div class="form-group">
        <div class="col-sm-2"> </div>
        <small id="resolved_dst" class="col-sm-10"></small>
    </div>

  </fieldset>

  <fieldset>
    <legend>Services</legend>

    <div class="row">
        <%= f.label "service_ids", class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
            <div class="input-group input-group-sm select2-bootstrap-prepend">
                <%= f.select :service_ids, {}, {}, { class: "form-control", multiple: true } %>
            </div>
        </div>
    </div>

    <div class="row">
        <%= f.label "group_ids", class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
            <div class="input-group input-group-sm select2-bootstrap-prepend">
                <%= f.select :group_ids, {}, {}, { class: "form-control", multiple: true } %>
            </div>
        </div>
    </div>

  </fieldset>

  <br />
  <br />

  <div class="row">
    <div class="actions col-sm-2">
      <%= f.submit 'Save changes', class: "btn btn-success" %>
    </div>
  </div>
<% end %>

<br />

<script type="text/javascript">
$(document).ready(function() {
function formatService(service) { return service.text }
function formatServiceSelection(service){ return service.text }

$("#rule_src_addr").change(function() {
    $.ajax({
        url: "/reverse",
        data: { ip: $("#rule_src_addr").val() }, 
        dataType: "json",
        success: function(data) {
            $("#resolved_src").text("");
            $.each(data, function(i, item) {
                if (item.hostname) {
                    $("#resolved_src").text(item.hostname);
                }
            });
        }
    });
});

$("#rule_dst_addr").change(function() {
    $.ajax({
        url: "/reverse",
        data: { ip: $("#rule_dst_addr").val() }, 
        dataType: "json",
        success: function(data) {
            $("#resolved_dst").text("");
            $.each(data, function(i, item) {
                if (item.hostname) {
                    $("#resolved_dst").text(item.hostname);
                }
            });
        }
    });
});

var $element = $("#rule_service_ids").select2({
    placeholder: "Select a service...",
    ajax: {
        url: "<%= services_path(format: :json) %>",
        dataType: 'json',
        delay: 250,
        data: function (params) {
            return {
                name: params.term,
                page: params.page
            };
        },
        processResults: function (data, page) {
            var newData = [];
            data.forEach(function (i, item) {
                newData.push({
                    id: i.id,
                    text: i.name
                });
            });
            return { results: newData };
        },
        cache: true
    },
    theme: 'bootstrap',
    allowClear: true,
    escapeMarkup: function (markup) { return markup; },
    minimumInputLength: 1,
    templateResult: formatService,
    templateSelection: formatServiceSelection
});

var some_data = <%= raw @rule_services || [] %>;

for (var d = 0; d < some_data.length; d++) {
    var item = some_data[d];
    var option = new Option(item[1], item[0], true, true);
    $element.append(option);
}
$element.trigger('change');

var $groups_element = $("#rule_group_ids").select2({
    placeholder: "Select a group...",
    ajax: {
        url: "<%= groups_path(format: :json) %>",
        dataType: 'json',
        delay: 250,
        data: function (params) {
            return {
                name: params.term,
                page: params.page
            };
        },
        processResults: function (data, page) {
            var newData = [];
            data.forEach(function (i, item) {
                newData.push({
                    id: i.id,
                    text: i.name
                });
            });
            return { results: newData };
        },
        cache: true
    },
    theme: 'bootstrap',
    allowClear: true,
    escapeMarkup: function (markup) { return markup; },
    minimumInputLength: 1,
    templateResult: formatService,
    templateSelection: formatServiceSelection
});

var group_data = <%= raw @rule_groups || [] %>;

for (var d = 0; d < group_data.length; d++) {
    var item = group_data[d];
    var option = new Option(item[1], item[0], true, true);
    $groups_element.append(option);
}
$groups_element.trigger('change');

});
</script>

app/views/rules/edit.html.erb
<div class="page-header">
  <h1>Editing Rule</h1>
</div>

<%= render 'form' %> <%= link_to 'Abort', @rule, class: "btn btn-danger" %>

app/views/rules/index.html.erb
<p class="text-success"><%= notice %></p>

<div class="page-header">
  <h1>Listing Rules</h1>
</div>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>ID</th>
      <th>Action</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Services</th>
      <th>Groups</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.id %></td>
        <td><%= rule.action %></td>
        <td><%= rule.src_addr %></td>
        <td><%= rule.dst_addr %></td>
        <td>
        <% rule.services.each do |service| -%>
          <p><%= service.name %></p>
        <% end %>
        </td>
        <td>
        <% rule.groups.each do |group| -%>
          <p><%= group.name %></p>
        <% end %>
        </td>
        <td><%= rule.description %></td>
        <td><%= link_to 'Details', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Delete', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path, :class => 'btn btn-primary' %>

app/views/rules/new.html.erb
<div class="page-header">
  <h1>New Rule</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back to overview', rules_path, :class => "btn btn-default" %>

app/views/rules/show.html.erb
<div class="row">
  <h2>Details</h2>
</div>

<div class="row">
  <p id="notice" class="text-success"> <%= notice %> </p>
</div>

<div class="row">
  <p>
    <strong>Description:</strong>
    <%= @rule.description %>
  </p>
</div>
  
<div class="row">
  <p>
    <strong>Action:</strong>
    <%= @rule.action %>
  </p>
</div>
  
<div class="row">
  <p>
    <strong>Source Address:</strong>
    <%= @rule.src_addr %>
  </p>
</div>
  
<div class="row">
  <p>
    <strong>Destination Address:</strong>
    <%= @rule.dst_addr %>
  </p>
</div>
  
<div class="row">
  <p>
    <strong>Services:</strong>
    <ul>
    <% @rule.services.each do |service| %>
      <li><%= service.name %></li>
    <% end %>
    </ul>
  </p>
</div>
  
<div class="row">
  <p>
    <strong>Groups:</strong>
    <ul>
    <% @rule.groups.each do |group| %>
      <li><%= group.name %></li>
    <% end %>
    </ul>
  </p>
</div>

<div class="row">
    <h2>Packet Tracer <small>Phases</small></h2>
    <% unless @phases.nil? %>
        <%= render partial: 'layouts/hash_table', object: @phases, as: 'table' %>
    <% end %>
</div>

<div class="row">
    <h2>Packet Tracer <small>Result</small></h2>
    <%= render partial: 'layouts/hash_table', object: @result, as: 'table' %>
</div>

<div class="row">
  <%= link_to 'Edit', edit_rule_path(@rule), :class => 'btn btn-primary' %> |
  <%= link_to 'Back to overview', rules_path, :class => 'btn btn-default' %>
</div>