config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :services
  devise_for :users
  resources :rules
  resources :users
  get 'reverse', to: 'dns#reverse'
  get 'forward', to: 'dns#forward'

  root to: 'welcome#index'

end

app/views/layouts/_hash_table.erb
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <% table[0].each_key do |th| %>
                <th><%= th %></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% table.each do |row| %>
            <tr>
                <% row.each_value do |td| %>
                <td><%= td %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
  <li><%= link_to 'Rules', rules_path %></li>
  <li><%= link_to 'Services', services_path %></li>
  <li><%= link_to 'Groups', groups_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Firewall Dashboard" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </main>
</body>
</html>